edition = "2024"
style_edition = "2024"

max_width = 100
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
